name: Docker Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Version
        run: echo "VERSION=1.0.0" >> $GITHUB_ENV

      - name: Build Image
        run: docker build -t my-app:${{ env.VERSION }} .
